### ISSUE TITLE
Latest entry shows incorrect timestamp on changeless publish

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-versioned-snapshot-admin#49] opened 2021-04-09 05:09 UTC
If a page is not edited when a publish action is undertaken (and nor does it have child content that is edited e.g. elemental blocks), the most recent snapshot entry on the history tab is updated to record the timestamp of the most recent publish action, losing the correct time of when the action it represents was undertaken.

This adversely affects auditable history.

Highly related (and steps to reproduce): https://github.com/silverstripe/silverstripe-versioned/issues/330

**Comment by unclecheese** [comment] 2021-04-19 00:29
The publish handler in snapshots uses the most recent `ChangeSet` as its source of truth. In a changeless publish, this change set will always be populated. Appears to be a symptom of the versioned issue mentioned above.

**Comment by unclecheese** [comment] 2021-04-19 01:13
Fix would be to test each change set item and look for at least one `CHANGE_MODIFIED` or `CHANGE_CREATED` and if not present, skip the snapshot.

**Comment by NightJar** [comment] 2021-04-19 04:33
Have you been able to reproduce this? I have had such great trouble in trying to distill this problem for this report that I'm no longer certain I wasn't just confused in the first place.

I'm thinking to simply close this - it can always be reopened or recreated if I do eventually encounter the problem as described again.

**Comment by unclecheese** [comment] 2021-04-27 20:34
Closing this as unable to reproduce.

**Closed by unclecheese** 2021-04-27 20:34 UTC
Labels: bug, invalid
